# Generated by Django 6.0.3 on 2026-05-10 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_fix_routine_client_to_people_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[
                    django.core.validators.EmailValidator("el email no es valido")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Femenino", "Femenino"),
                    ("Masculino", "Masculino"),
                    ("Otro", "Otro"),
                ],
                max_length=10,
                verbose_name="genero",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="id_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        100000,
                        "el dni debe tener al menos 6 digitos, ingrese un dni valido",
                    ),
                    django.core.validators.MaxValueValidator(
                        9999999999,
                        "el dni debe tener un maximo de 10 digitos, ingrese un numero valido",
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "el nombre debe tener almenos 2 caracteres"
                    ),
                    django.core.validators.MaxLengthValidator(
                        40, "el nombre no debe superar los 40 caracteres"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(
                blank=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        8, "el numero de telefono debe tener al menos 8 caracteres"
                    ),
                    django.core.validators.MaxLengthValidator(
                        20, "el numero de telefono no debe superar los 20 caracteres"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="surname",
            field=models.CharField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "el apellido debe tener almenos 2 caracteres"
                    ),
                    django.core.validators.MaxLengthValidator(
                        40, "el apellido no debe superar los 40 caracteres"
                    ),
                ]
            ),
        ),
    ]
