# Generated by Django 6.0.3 on 2026-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=60, null=True)),
                ("descripcion", models.CharField(blank=True, max_length=60, null=True)),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
