# Generated by Django 6.0.5 on 2026-10-01 19:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Se guarda como el primer día del mes.', verbose_name='Mes de la cuota')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe')),
                ('due_date', models.DateField(verbose_name='Vencimiento')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], max_length=12, verbose_name='Medio de pago')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia del comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_payments', to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_monthly_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensualidad',
                'verbose_name_plural': 'mensualidades',
                'ordering': ['-period', 'member__username'],
                'constraints': [models.UniqueConstraint(fields=('member', 'period'), name='unique_member_month'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='monthly_payment_positive_amount'), models.CheckConstraint(condition=models.Q(models.Q(('method', ''), ('paid_on__isnull', True)), models.Q(('paid_on__isnull', False), models.Q(('method', ''), _negated=True)), _connector='OR'), name='monthly_payment_payment_details')],
            },
        ),
    ]
