# Generated by Django 6.1.1 on 2026-10-04 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("pagos", "0001_initial"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="PaymentMovement",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"amount",
					models.DecimalField(
						decimal_places=2, max_digits=10, verbose_name="Monto"
					),
				),
				("paid_on", models.DateField(verbose_name="Fecha")),
				(
					"method",
					models.CharField(
						choices=[
							("cash", "Efectivo"),
							("transfer", "Transferencia"),
							("card", "Tarjeta"),
						],
						max_length=12,
					),
				),
				("reference", models.CharField(blank=True, max_length=100)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				(
					"charge",
					models.ForeignKey(
						on_delete=django.db.models.deletion.PROTECT,
						related_name="movements",
						to="pagos.monthlypayment",
					),
				),
				(
					"recorded_by",
					models.ForeignKey(
						editable=False,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"reversal_of",
					models.OneToOneField(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.PROTECT,
						related_name="reversal",
						to="pagos.paymentmovement",
					),
				),
			],
			options={
				"ordering": ["-created_at", "-pk"],
				"constraints": [
					models.CheckConstraint(
						condition=models.Q(
							models.Q(
								("amount__gt", 0), ("reversal_of__isnull", True)
							),
							models.Q(
								("amount__lt", 0),
								("reversal_of__isnull", False),
							),
							_connector="OR",
						),
						name="payment_movement_sign",
					)
				],
			},
		),
	]
