# Generated by Django 6.1.1 on 2026-10-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		("pagos", "0003_import_payment_history"),
	]

	operations = [
		migrations.RemoveConstraint(
			model_name="monthlypayment",
			name="monthly_payment_payment_details",
		),
		migrations.RemoveField(
			model_name="paymentmovement",
			name="method",
		),
		migrations.RemoveField(
			model_name="monthlypayment",
			name="method",
		),
	]
