# Generated by Django 6.0.5 on 2026-10-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='items',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalle de precios'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='kind',
            field=models.CharField(choices=[('gym', 'Musculación'), ('classes', 'Clases'), ('both', 'Musculación y clases')], default='gym', max_length=12, verbose_name='Concepto'),
        ),
    ]
