# Generated by Django 6.0.3 on 2026-03-22 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rutina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("genero", models.CharField(max_length=10)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "id_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planes.plan",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rutina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.rutina"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RutinaEjercicioDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repeticiones", models.IntegerField(blank=True, null=True)),
                ("sets", models.IntegerField(blank=True, null=True)),
                ("fallo", models.CharField(default="No", max_length=7)),
                (
                    "dias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.dia"
                    ),
                ),
                (
                    "ejercicios",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.ejercicio",
                    ),
                ),
                (
                    "rutina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios_dias",
                        to="login.rutina",
                    ),
                ),
            ],
        ),
    ]
