# Generated by Django 5.2.8 on 2025-11-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_dia_ejercicio_rutina_persona_rutina_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rutina",
            name="nombre",
        ),
        migrations.AddField(
            model_name="rutinaejerciciodia",
            name="fallo",
            field=models.CharField(default="No", max_length=7),
        ),
        migrations.AddField(
            model_name="rutinaejerciciodia",
            name="repeticiones",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rutinaejerciciodia",
            name="sets",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
