# Generated by Django 5.2.8 on 2025-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_persona_usuario_membresia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=60, null=True)),
                ("descripcion", models.CharField(blank=True, max_length=60, null=True)),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
