# Generated by Django 5.2.8 on 2025-12-03 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_persona_id_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="membresia",
            name="id_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.plan",
            ),
        ),
    ]
