# Generated by Django 6.0.3 on 2026-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=60, null=True)),
                ("description", models.CharField(blank=True, max_length=60, null=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "planes_plan",
            },
        ),
    ]
