# Generated by Django 6.0.3 on 2026-03-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="plan",
            table=None,
        ),
    ]
