# Generated by Django 6.0.3 on 2026-04-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_alter_plan_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="plan",
            table="planes_plan",
        ),
    ]
