# Generated by Django 6.0.5 on 2026-10-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("plans", "0004_alter_plan_base_price"),
	]

	operations = [
		migrations.AlterField(
			model_name="plan",
			name="description",
			field=models.CharField(blank=True, max_length=180, null=True),
		),
	]
