# Generated by Django 6.0.3 on 2026-05-10 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(
                default="sin descripcion",
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "la descripcion debe tener al menos 5 caracteres"
                    ),
                    django.core.validators.MaxLengthValidator(
                        150, "la descripcion debe tener como maximo 150 caracteres"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "El nombre de la clase debe tener almenos 3 caracteres"
                    ),
                    django.core.validators.MaxLengthValidator(
                        30, "el nombre de la clase no debe superar los 30 caracteres"
                    ),
                ],
            ),
        ),
    ]
