# Generated by Django 6.1 on 2026-09-15 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_course_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="max_capacity",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "la capacidad maxima de alumnos debe ser al menos 1"
                    )
                ],
            ),
        ),
    ]
