# Generated by Django 6.0.5 on 2026-09-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_inscription_unique_course_participant"),
        ("classes", "0006_alter_course_max_capacity"),
    ]

    operations = []
